<? partial('firstscreen'); ?>
<? partial('advantages'); ?>
<? partial('catalog'); ?>
<? partial('windowsScreen'); ?>
<? partial('portfolio'); ?> 
<? partial('gate'); ?> 
<? partial('payment'); ?> 
<? partial('phase'); ?> 
<? partial('delivery'); ?> 
<? partial('scheme'); ?> 
<? partial('projects'); ?> 